name: Update flake inputs

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    # Run weekly on Sunday at 00:00
    - cron: "0 0 * * 0"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup binary cache
        uses: cachix/cachix-action@v14
        with:
          name: seadome
          extraPullNames: dotfield,nix-community
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Update flake.lock
        run: nix flake update

      - name: Build devshell dependencies
        run: nix build .#devShells.x86_64-linux.default

      # <https://github.com/marketplace/actions/create-pull-request>
      - name: Commit and create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(deps:nix): update flake inputs"
          title: "Update flake inputs"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated
            scope:prj

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: Enable pull request automerge
        run: gh pr merge --merge --auto ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
